apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook
spec:
  selector:
    matchLabels:
      app: guestbook
  template:
    metadata:
      labels:
        app: guestbook
    spec:
      containers:
        - image: okteto.dev/guestbook:1.0.0
          name: guestbook
          env:
            - name: REDIS_HOST
              value: redis

---

apiVersion: v1
kind: Service
metadata:
  name: guestbook
spec:
  type: ClusterIP
  ports:
    - name: guestbook
      port: 8080
  selector:
    app: guestbook

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: guestbook
  annotations:
    dev.okteto.com/generate-host: guestbook
spec:
  rules:
    - http:
        paths:
          - backend:
              service:
                name: guestbook
                port:
                  number: 8080
            path: /
            pathType: ImplementationSpecific

